// cr_c_history.xs - XQ filter (screener) script C: daily history for research
// Chip Radar TW R3 peer spillover + strong-chip persistence (2026-10-08).
// NOT a trading signal; every stock passes. Run once over all listed + OTC
// stocks, daily frequency, then export.
// Owner rule exception (2026-10-08): only the GetField field names are
// Chinese; everything else is ASCII.
// v3 (2026-10-08): uses only the constructs that already compiled and ran
// in probe_chip_fields.xs on the owner's XQ (single-line var, boolean +
// not, for, if/then/else, GetField(...)[i], 4-argument OutputField,
// ret = 1). No IsLastBar, no Close, no arrays, no variable named v (V may
// be the Volume shorthand).
//
// Columns 1-60 : mfr_d0 .. mfr_d59  main-force net / volume (d0 = today,
//                d1 = 1 trading day ago ...; 0 when volume is 0)
// Columns 61-99: t10r_d0 .. t10r_d38  top-10 brokers net / volume
// (99 = the OutputField index limit: one run carries the most data)

var: volDay(0), val(0);

SetBarFreq("D");
SetTotalBar(65);

ret = 1;

volDay = GetField("成交量", "D")[0];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[0] / volDay;
OutputField(1, val, 4, "mfr_d0");
volDay = GetField("成交量", "D")[1];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[1] / volDay;
OutputField(2, val, 4, "mfr_d1");
volDay = GetField("成交量", "D")[2];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[2] / volDay;
OutputField(3, val, 4, "mfr_d2");
volDay = GetField("成交量", "D")[3];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[3] / volDay;
OutputField(4, val, 4, "mfr_d3");
volDay = GetField("成交量", "D")[4];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[4] / volDay;
OutputField(5, val, 4, "mfr_d4");
volDay = GetField("成交量", "D")[5];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[5] / volDay;
OutputField(6, val, 4, "mfr_d5");
volDay = GetField("成交量", "D")[6];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[6] / volDay;
OutputField(7, val, 4, "mfr_d6");
volDay = GetField("成交量", "D")[7];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[7] / volDay;
OutputField(8, val, 4, "mfr_d7");
volDay = GetField("成交量", "D")[8];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[8] / volDay;
OutputField(9, val, 4, "mfr_d8");
volDay = GetField("成交量", "D")[9];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[9] / volDay;
OutputField(10, val, 4, "mfr_d9");
volDay = GetField("成交量", "D")[10];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[10] / volDay;
OutputField(11, val, 4, "mfr_d10");
volDay = GetField("成交量", "D")[11];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[11] / volDay;
OutputField(12, val, 4, "mfr_d11");
volDay = GetField("成交量", "D")[12];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[12] / volDay;
OutputField(13, val, 4, "mfr_d12");
volDay = GetField("成交量", "D")[13];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[13] / volDay;
OutputField(14, val, 4, "mfr_d13");
volDay = GetField("成交量", "D")[14];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[14] / volDay;
OutputField(15, val, 4, "mfr_d14");
volDay = GetField("成交量", "D")[15];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[15] / volDay;
OutputField(16, val, 4, "mfr_d15");
volDay = GetField("成交量", "D")[16];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[16] / volDay;
OutputField(17, val, 4, "mfr_d16");
volDay = GetField("成交量", "D")[17];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[17] / volDay;
OutputField(18, val, 4, "mfr_d17");
volDay = GetField("成交量", "D")[18];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[18] / volDay;
OutputField(19, val, 4, "mfr_d18");
volDay = GetField("成交量", "D")[19];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[19] / volDay;
OutputField(20, val, 4, "mfr_d19");
volDay = GetField("成交量", "D")[20];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[20] / volDay;
OutputField(21, val, 4, "mfr_d20");
volDay = GetField("成交量", "D")[21];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[21] / volDay;
OutputField(22, val, 4, "mfr_d21");
volDay = GetField("成交量", "D")[22];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[22] / volDay;
OutputField(23, val, 4, "mfr_d22");
volDay = GetField("成交量", "D")[23];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[23] / volDay;
OutputField(24, val, 4, "mfr_d23");
volDay = GetField("成交量", "D")[24];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[24] / volDay;
OutputField(25, val, 4, "mfr_d24");
volDay = GetField("成交量", "D")[25];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[25] / volDay;
OutputField(26, val, 4, "mfr_d25");
volDay = GetField("成交量", "D")[26];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[26] / volDay;
OutputField(27, val, 4, "mfr_d26");
volDay = GetField("成交量", "D")[27];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[27] / volDay;
OutputField(28, val, 4, "mfr_d27");
volDay = GetField("成交量", "D")[28];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[28] / volDay;
OutputField(29, val, 4, "mfr_d28");
volDay = GetField("成交量", "D")[29];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[29] / volDay;
OutputField(30, val, 4, "mfr_d29");
volDay = GetField("成交量", "D")[30];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[30] / volDay;
OutputField(31, val, 4, "mfr_d30");
volDay = GetField("成交量", "D")[31];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[31] / volDay;
OutputField(32, val, 4, "mfr_d31");
volDay = GetField("成交量", "D")[32];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[32] / volDay;
OutputField(33, val, 4, "mfr_d32");
volDay = GetField("成交量", "D")[33];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[33] / volDay;
OutputField(34, val, 4, "mfr_d33");
volDay = GetField("成交量", "D")[34];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[34] / volDay;
OutputField(35, val, 4, "mfr_d34");
volDay = GetField("成交量", "D")[35];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[35] / volDay;
OutputField(36, val, 4, "mfr_d35");
volDay = GetField("成交量", "D")[36];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[36] / volDay;
OutputField(37, val, 4, "mfr_d36");
volDay = GetField("成交量", "D")[37];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[37] / volDay;
OutputField(38, val, 4, "mfr_d37");
volDay = GetField("成交量", "D")[38];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[38] / volDay;
OutputField(39, val, 4, "mfr_d38");
volDay = GetField("成交量", "D")[39];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[39] / volDay;
OutputField(40, val, 4, "mfr_d39");
volDay = GetField("成交量", "D")[40];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[40] / volDay;
OutputField(41, val, 4, "mfr_d40");
volDay = GetField("成交量", "D")[41];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[41] / volDay;
OutputField(42, val, 4, "mfr_d41");
volDay = GetField("成交量", "D")[42];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[42] / volDay;
OutputField(43, val, 4, "mfr_d42");
volDay = GetField("成交量", "D")[43];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[43] / volDay;
OutputField(44, val, 4, "mfr_d43");
volDay = GetField("成交量", "D")[44];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[44] / volDay;
OutputField(45, val, 4, "mfr_d44");
volDay = GetField("成交量", "D")[45];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[45] / volDay;
OutputField(46, val, 4, "mfr_d45");
volDay = GetField("成交量", "D")[46];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[46] / volDay;
OutputField(47, val, 4, "mfr_d46");
volDay = GetField("成交量", "D")[47];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[47] / volDay;
OutputField(48, val, 4, "mfr_d47");
volDay = GetField("成交量", "D")[48];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[48] / volDay;
OutputField(49, val, 4, "mfr_d48");
volDay = GetField("成交量", "D")[49];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[49] / volDay;
OutputField(50, val, 4, "mfr_d49");
volDay = GetField("成交量", "D")[50];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[50] / volDay;
OutputField(51, val, 4, "mfr_d50");
volDay = GetField("成交量", "D")[51];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[51] / volDay;
OutputField(52, val, 4, "mfr_d51");
volDay = GetField("成交量", "D")[52];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[52] / volDay;
OutputField(53, val, 4, "mfr_d52");
volDay = GetField("成交量", "D")[53];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[53] / volDay;
OutputField(54, val, 4, "mfr_d53");
volDay = GetField("成交量", "D")[54];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[54] / volDay;
OutputField(55, val, 4, "mfr_d54");
volDay = GetField("成交量", "D")[55];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[55] / volDay;
OutputField(56, val, 4, "mfr_d55");
volDay = GetField("成交量", "D")[56];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[56] / volDay;
OutputField(57, val, 4, "mfr_d56");
volDay = GetField("成交量", "D")[57];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[57] / volDay;
OutputField(58, val, 4, "mfr_d57");
volDay = GetField("成交量", "D")[58];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[58] / volDay;
OutputField(59, val, 4, "mfr_d58");
volDay = GetField("成交量", "D")[59];
val = 0;
if volDay > 0 then val = GetField("主力買賣超張數", "D")[59] / volDay;
OutputField(60, val, 4, "mfr_d59");
volDay = GetField("成交量", "D")[0];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[0] / volDay;
OutputField(61, val, 4, "t10r_d0");
volDay = GetField("成交量", "D")[1];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[1] / volDay;
OutputField(62, val, 4, "t10r_d1");
volDay = GetField("成交量", "D")[2];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[2] / volDay;
OutputField(63, val, 4, "t10r_d2");
volDay = GetField("成交量", "D")[3];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[3] / volDay;
OutputField(64, val, 4, "t10r_d3");
volDay = GetField("成交量", "D")[4];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[4] / volDay;
OutputField(65, val, 4, "t10r_d4");
volDay = GetField("成交量", "D")[5];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[5] / volDay;
OutputField(66, val, 4, "t10r_d5");
volDay = GetField("成交量", "D")[6];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[6] / volDay;
OutputField(67, val, 4, "t10r_d6");
volDay = GetField("成交量", "D")[7];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[7] / volDay;
OutputField(68, val, 4, "t10r_d7");
volDay = GetField("成交量", "D")[8];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[8] / volDay;
OutputField(69, val, 4, "t10r_d8");
volDay = GetField("成交量", "D")[9];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[9] / volDay;
OutputField(70, val, 4, "t10r_d9");
volDay = GetField("成交量", "D")[10];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[10] / volDay;
OutputField(71, val, 4, "t10r_d10");
volDay = GetField("成交量", "D")[11];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[11] / volDay;
OutputField(72, val, 4, "t10r_d11");
volDay = GetField("成交量", "D")[12];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[12] / volDay;
OutputField(73, val, 4, "t10r_d12");
volDay = GetField("成交量", "D")[13];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[13] / volDay;
OutputField(74, val, 4, "t10r_d13");
volDay = GetField("成交量", "D")[14];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[14] / volDay;
OutputField(75, val, 4, "t10r_d14");
volDay = GetField("成交量", "D")[15];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[15] / volDay;
OutputField(76, val, 4, "t10r_d15");
volDay = GetField("成交量", "D")[16];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[16] / volDay;
OutputField(77, val, 4, "t10r_d16");
volDay = GetField("成交量", "D")[17];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[17] / volDay;
OutputField(78, val, 4, "t10r_d17");
volDay = GetField("成交量", "D")[18];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[18] / volDay;
OutputField(79, val, 4, "t10r_d18");
volDay = GetField("成交量", "D")[19];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[19] / volDay;
OutputField(80, val, 4, "t10r_d19");
volDay = GetField("成交量", "D")[20];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[20] / volDay;
OutputField(81, val, 4, "t10r_d20");
volDay = GetField("成交量", "D")[21];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[21] / volDay;
OutputField(82, val, 4, "t10r_d21");
volDay = GetField("成交量", "D")[22];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[22] / volDay;
OutputField(83, val, 4, "t10r_d22");
volDay = GetField("成交量", "D")[23];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[23] / volDay;
OutputField(84, val, 4, "t10r_d23");
volDay = GetField("成交量", "D")[24];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[24] / volDay;
OutputField(85, val, 4, "t10r_d24");
volDay = GetField("成交量", "D")[25];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[25] / volDay;
OutputField(86, val, 4, "t10r_d25");
volDay = GetField("成交量", "D")[26];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[26] / volDay;
OutputField(87, val, 4, "t10r_d26");
volDay = GetField("成交量", "D")[27];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[27] / volDay;
OutputField(88, val, 4, "t10r_d27");
volDay = GetField("成交量", "D")[28];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[28] / volDay;
OutputField(89, val, 4, "t10r_d28");
volDay = GetField("成交量", "D")[29];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[29] / volDay;
OutputField(90, val, 4, "t10r_d29");
volDay = GetField("成交量", "D")[30];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[30] / volDay;
OutputField(91, val, 4, "t10r_d30");
volDay = GetField("成交量", "D")[31];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[31] / volDay;
OutputField(92, val, 4, "t10r_d31");
volDay = GetField("成交量", "D")[32];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[32] / volDay;
OutputField(93, val, 4, "t10r_d32");
volDay = GetField("成交量", "D")[33];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[33] / volDay;
OutputField(94, val, 4, "t10r_d33");
volDay = GetField("成交量", "D")[34];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[34] / volDay;
OutputField(95, val, 4, "t10r_d34");
volDay = GetField("成交量", "D")[35];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[35] / volDay;
OutputField(96, val, 4, "t10r_d35");
volDay = GetField("成交量", "D")[36];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[36] / volDay;
OutputField(97, val, 4, "t10r_d36");
volDay = GetField("成交量", "D")[37];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[37] / volDay;
OutputField(98, val, 4, "t10r_d37");
volDay = GetField("成交量", "D")[38];
val = 0;
if volDay > 0 then val = GetField("綜合前十大券商買賣超張數", "D")[38] / volDay;
OutputField(99, val, 4, "t10r_d38");
